name: Release Gem

# Release process only gets run when paillier.gemspec gets changed in master.
on:
  push:
    branches:
      - 'master'
    paths:
      - 'paillier.gemspec'

jobs:
  release:
    # https://github.com/marketplace/actions/publish-to-rubygems
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - run: set +x
      - run: mkdir -p ~/.gem

      - name: Generate gem credentials
        run: |
          cat << EOF > ~/.gem/credentials
          ---
          :github: Bearer ${{ secrets.GITHUB_TOKEN }}
          :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
          EOF

      - name: Chmod file
        run: chmod 0600 ~/.gem/credentials

      - run: set -x

      - name: Install dependencies
        run: |
          echo "Installing dependencies..." &&
          bundle install > /dev/null

      - name: Release gem
        run: |
          echo "Running `rake release`" &&
          rake release